In [2]:
from sklearn.linear_model import RidgeClassifier
import numpy as np
import pandas as pd

In [3]:
features = pd.DataFrame()

In [29]:
model = RidgeClassifier(alpha=100)

In [30]:
features = pd.read_csv("CNNFeatureExtraction.csv")
features

Unnamed: 0    0         1         2         3    4    5         6    7  \
0             0  0.0  0.476364  2.021005  0.000000  0.0  0.0  1.254847  0.0   
1             1  0.0  1.389859  1.540506  0.000000  0.0  0.0  0.889042  0.0   
2             2  0.0  0.665737  2.095717  0.420907  0.0  0.0  1.225297  0.0   
3             3  0.0  0.666845  1.767537  0.000000  0.0  0.0  1.318400  0.0   
4             4  0.0  1.029707  1.438789  0.280908  0.0  0.0  0.553397  0.0   
..          ...  ...       ...       ...       ...  ...  ...       ...  ...   
115         115  0.0  0.149788  1.602545  0.000000  0.0  0.0  1.099699  0.0   
116         116  0.0  0.486703  1.218230  0.000000  0.0  0.0  0.062852  0.0   
117         117  0.0  0.733696  1.766389  0.000000  0.0  0.0  0.481217  0.0   
118         118  0.0  0.793202  1.739536  0.000000  0.0  0.0  0.944209  0.0   
119         119  0.0  0.000000  1.968359  0.000000  0.0  0.0  0.562202  0.0   

       8  ...  4087      4088      4089  4090      4091      4092  4093  4094  \
0    0.0  ...   0.0  0.562407  2.212515   0.0  0.000000  0.000000   0.0   0.0   
1    0.0  ...   0.0  0.657191  2.172289   0.0  0.000000  0.076213   0.0   0.0   
2    0.0  ...   0.0  0.949781  2.475493   0.0  0.351266  0.885684   0.0   0.0   
3    0.0  ...   0.0  0.487599  2.173003   0.0  0.384365  0.233875   0.0   0.0   
4    0.0  ...   0.0  1.150887  2.766511   0.0  0.000000  0.049240   0.0   0.0   
..   ...  ...   ...       ...       ...   ...       ...       ...   ...   ...   
115  0.0  ...   0.0  0.981983  2.833213   0.0  0.000000  0.000000   0.0   0.0   
116  0.0  ...   0.0  0.810484  3.355525   0.0  0.000000  0.000000   0.0   0.0   
117  0.0  ...   0.0  0.424269  2.923443   0.0  0.000000  0.000000   0.0   0.0   
118  0.0  ...   0.0  0.135666  2.272999   0.0  0.000000  0.000000   0.0   0.0   
119  0.0  ...   0.0  0.981644  3.041615   0.0  0.000000  0.000000   0.0   0.0   

         4095   diag  
0    1.675843  DYSGR  
1    1.661323  DYSGR  
2    1.072596  DYSGR  
3    1.723757  DYSGR  
4    2.183215  DYSGR  
..        ...    ...  
115  1.840923      0  
116  2.068771      0  
117  1.504338      0  
118  2.092905      0  
119  1.802847      0  

[120 rows x 4098 columns]

In [31]:
features.drop(["Unnamed: 0"], axis=1, inplace=True)
features

0         1         2         3    4    5         6    7    8    9  \
0    0.0  0.476364  2.021005  0.000000  0.0  0.0  1.254847  0.0  0.0  0.0   
1    0.0  1.389859  1.540506  0.000000  0.0  0.0  0.889042  0.0  0.0  0.0   
2    0.0  0.665737  2.095717  0.420907  0.0  0.0  1.225297  0.0  0.0  0.0   
3    0.0  0.666845  1.767537  0.000000  0.0  0.0  1.318400  0.0  0.0  0.0   
4    0.0  1.029707  1.438789  0.280908  0.0  0.0  0.553397  0.0  0.0  0.0   
..   ...       ...       ...       ...  ...  ...       ...  ...  ...  ...   
115  0.0  0.149788  1.602545  0.000000  0.0  0.0  1.099699  0.0  0.0  0.0   
116  0.0  0.486703  1.218230  0.000000  0.0  0.0  0.062852  0.0  0.0  0.0   
117  0.0  0.733696  1.766389  0.000000  0.0  0.0  0.481217  0.0  0.0  0.0   
118  0.0  0.793202  1.739536  0.000000  0.0  0.0  0.944209  0.0  0.0  0.0   
119  0.0  0.000000  1.968359  0.000000  0.0  0.0  0.562202  0.0  0.0  0.0   

     ...  4087      4088      4089  4090      4091      4092  4093  4094  \
0    ...   0.0  0.562407  2.212515   0.0  0.000000  0.000000   0.0   0.0   
1    ...   0.0  0.657191  2.172289   0.0  0.000000  0.076213   0.0   0.0   
2    ...   0.0  0.949781  2.475493   0.0  0.351266  0.885684   0.0   0.0   
3    ...   0.0  0.487599  2.173003   0.0  0.384365  0.233875   0.0   0.0   
4    ...   0.0  1.150887  2.766511   0.0  0.000000  0.049240   0.0   0.0   
..   ...   ...       ...       ...   ...       ...       ...   ...   ...   
115  ...   0.0  0.981983  2.833213   0.0  0.000000  0.000000   0.0   0.0   
116  ...   0.0  0.810484  3.355525   0.0  0.000000  0.000000   0.0   0.0   
117  ...   0.0  0.424269  2.923443   0.0  0.000000  0.000000   0.0   0.0   
118  ...   0.0  0.135666  2.272999   0.0  0.000000  0.000000   0.0   0.0   
119  ...   0.0  0.981644  3.041615   0.0  0.000000  0.000000   0.0   0.0   

         4095   diag  
0    1.675843  DYSGR  
1    1.661323  DYSGR  
2    1.072596  DYSGR  
3    1.723757  DYSGR  
4    2.183215  DYSGR  
..        ...    ...  
115  1.840923      0  
116  2.068771      0  
117  1.504338      0  
118  2.092905      0  
119  1.802847      0  

[120 rows x 4097 columns]

In [32]:
diag = []

diagnosi = features["diag"]

for elem in diagnosi:
    if elem == "DYSGR":
        diag.append(1)
    else:
        diag.append(0)

In [33]:
features.drop(["diag"], axis=1, inplace=True)
features["diag"] = diag
features

0         1         2         3    4    5         6    7    8    9  \
0    0.0  0.476364  2.021005  0.000000  0.0  0.0  1.254847  0.0  0.0  0.0   
1    0.0  1.389859  1.540506  0.000000  0.0  0.0  0.889042  0.0  0.0  0.0   
2    0.0  0.665737  2.095717  0.420907  0.0  0.0  1.225297  0.0  0.0  0.0   
3    0.0  0.666845  1.767537  0.000000  0.0  0.0  1.318400  0.0  0.0  0.0   
4    0.0  1.029707  1.438789  0.280908  0.0  0.0  0.553397  0.0  0.0  0.0   
..   ...       ...       ...       ...  ...  ...       ...  ...  ...  ...   
115  0.0  0.149788  1.602545  0.000000  0.0  0.0  1.099699  0.0  0.0  0.0   
116  0.0  0.486703  1.218230  0.000000  0.0  0.0  0.062852  0.0  0.0  0.0   
117  0.0  0.733696  1.766389  0.000000  0.0  0.0  0.481217  0.0  0.0  0.0   
118  0.0  0.793202  1.739536  0.000000  0.0  0.0  0.944209  0.0  0.0  0.0   
119  0.0  0.000000  1.968359  0.000000  0.0  0.0  0.562202  0.0  0.0  0.0   

     ...  4087      4088      4089  4090      4091      4092  4093  4094  \
0    ...   0.0  0.562407  2.212515   0.0  0.000000  0.000000   0.0   0.0   
1    ...   0.0  0.657191  2.172289   0.0  0.000000  0.076213   0.0   0.0   
2    ...   0.0  0.949781  2.475493   0.0  0.351266  0.885684   0.0   0.0   
3    ...   0.0  0.487599  2.173003   0.0  0.384365  0.233875   0.0   0.0   
4    ...   0.0  1.150887  2.766511   0.0  0.000000  0.049240   0.0   0.0   
..   ...   ...       ...       ...   ...       ...       ...   ...   ...   
115  ...   0.0  0.981983  2.833213   0.0  0.000000  0.000000   0.0   0.0   
116  ...   0.0  0.810484  3.355525   0.0  0.000000  0.000000   0.0   0.0   
117  ...   0.0  0.424269  2.923443   0.0  0.000000  0.000000   0.0   0.0   
118  ...   0.0  0.135666  2.272999   0.0  0.000000  0.000000   0.0   0.0   
119  ...   0.0  0.981644  3.041615   0.0  0.000000  0.000000   0.0   0.0   

         4095  diag  
0    1.675843     1  
1    1.661323     1  
2    1.072596     1  
3    1.723757     1  
4    2.183215     1  
..        ...   ...  
115  1.840923     0  
116  2.068771     0  
117  1.504338     0  
118  2.092905     0  
119  1.802847     0  

[120 rows x 4097 columns]

In [34]:
from sklearn.model_selection import train_test_split

In [35]:
train, test = train_test_split(features, test_size=20)

In [36]:
trainY = train["diag"]
trainX = train.drop(["diag"], axis=1)

testY = test["diag"]
testX = test.drop(["diag"], axis=1)

In [37]:
model.fit(trainX, trainY)

RidgeClassifier(alpha=100)

In [38]:
results = model.predict(testX)
results

array([0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1])

In [39]:
print(model.score(testX,testY))

0.9


In [15]:
from sklearn.linear_model import LogisticRegression

In [40]:
logModel = LogisticRegression()

logModel.fit(trainX, trainY)

results = logModel.predict(testX)
results

/home/andrea/anaconda3/envs/tf/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1])

In [41]:
print(logModel.score(testX,testY))

0.8


In [42]:
from sklearn.tree import DecisionTreeClassifier

In [43]:
tree = DecisionTreeClassifier()

tree.fit(trainX, trainY)

results = tree.predict(testX)
results

array([1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0])

In [44]:
print(tree.score(testX,testY))

0.6
